---
version: "3.2"
services:

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
      
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /data/torrents:/data/torrents
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    
  jellyfin:
    image: cr.hotio.dev/hotio/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data/media:/data/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    
  jackett:
    image: cr.hotio.dev/hotio/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
    volumes:
      - /docker/appdata/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
